### GENERAL SETTINGS ###

# Site settings

title: Ryuji Mano
description: "My personal website using the Solid theme with Jekyll"
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "ryujimano.github.io"


# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"


### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: facebook
    url: https://facebook.com/ryuji.mano.3
  - title: github
    url: https://github.com/ryujimano
  - title: linkedin
    url: https://linkedin.com/in/ryujimano

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - 1275 First Street
    - West Lafayette, IN 47906
    - United States
email: rmano@purdue.edu
tel: +724 988-8445


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Ryuji Mano
    position: B.S. Computer Science '19
    text: Hello, my name is Ryuji Mano. I am currently a freshman at Purdue University studying Computer Science. I love working with Swift and iOS Development.
    img: PUIDPhoto.jpg
    social:
      - title: envelope #use for email address
        url: mailto:rmano@purdue.edu
      - title: linkedin
        url: http://linkedin.com/in/ryujimano

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Hello, my name is Ryuji Mano. I am a freshman at Purdue University studying Computer Science."
